[package]
name = "pika-test"
version = "0.0.1"
edition = "2021"
description = "A Behavior-Driven Development test framework for Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
